runtime: nodejs14
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: public/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: public/index.html
    upload: public/index.html
