---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/clinical-papers
  label: Clinical Papers
  create: all
  match: "**/*"
  new_doc_ext: ".json"
  templates:
  - clinical-paper
- type: directory
  path: content/terms-and-conditions
  label: T&C
  create: all
  match: "**/*"
  templates:
  - t-c
- type: document
  path: content/menu.json
  label: Menu
- type: directory
  path: content/promotions
  label: Promotions
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - updates
- type: directory
  path: content/health-tips
  label: Health Tips
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - updates
- type: directory
  path: content/updates
  label: Updates
  create: all
  match: "**/*"
  new_doc_ext: md
  templates:
  - updates
upload_dir: content/images
public_path: "../images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: "/public"
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:14
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn build
